### ISSUE TITLE
Move gcode from root folder breaks thumbnail link

### ISSUE THREAD

**Issue by coelholm** [jneilliii/OctoPrint-UltimakerFormatPackage#40] opened 2021-03-11 14:19 UTC
When I move gcode files to a subfolder it breaks thumbnail link.  I tried to manually move files and reflect same folder structure under .octoprint/data/UltimakerFormatPackage, but it didn't help (It worked in the past).

**Comment by jneilliii** [comment] 2021-03-11 14:42
seems to be a duplicate of #23 and/or #10 which were reported as resolved. Unless this is a regression of some kind or the files are being moved outside of OctoPrint's interface I can't think of a reason that this would be happening.

**Closed as completed** 2021-04-02 00:14 UTC
